-- Migrasi Upload Foto dan Dokumentasi Koin NU Ranting
-- Jalankan sekali di Supabase SQL Editor setelah schema awal sudah terpasang.

alter table pengambilan_koin add column if not exists bukti_foto_path text;
alter table pengambilan_koin add column if not exists bukti_foto_url text;
alter table pengambilan_koin add column if not exists bukti_foto_nama text;

alter table verifikasi_setoran add column if not exists bukti_setoran_path text;
alter table verifikasi_setoran add column if not exists bukti_setoran_url text;
alter table verifikasi_setoran add column if not exists bukti_setoran_nama text;

alter table penyaluran_dana add column if not exists dokumentasi_path text;
alter table penyaluran_dana add column if not exists dokumentasi_url text;
alter table penyaluran_dana add column if not exists dokumentasi_nama text;

create table if not exists dokumentasi_kegiatan (
  id bigint generated by default as identity primary key,
  judul text not null,
  kategori text not null,
  tanggal date not null,
  foto_path text,
  foto_url text not null,
  foto_nama text,
  created_at timestamptz not null default now()
);

alter table dokumentasi_kegiatan enable row level security;

drop policy if exists "publik baca dokumentasi kegiatan" on dokumentasi_kegiatan;
create policy "publik baca dokumentasi kegiatan"
on dokumentasi_kegiatan for select
using (true);

drop policy if exists "admin bendahara kelola dokumentasi kegiatan" on dokumentasi_kegiatan;
create policy "admin bendahara kelola dokumentasi kegiatan"
on dokumentasi_kegiatan for all
using (current_app_role() in ('admin', 'bendahara'))
with check (current_app_role() in ('admin', 'bendahara'));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'koin-nu-public-documentation',
  'koin-nu-public-documentation',
  true,
  2097152,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'koin-nu-private-evidence',
  'koin-nu-private-evidence',
  false,
  2097152,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "publik baca dokumentasi storage" on storage.objects;
create policy "publik baca dokumentasi storage"
on storage.objects for select
using (bucket_id = 'koin-nu-public-documentation');

drop policy if exists "admin bendahara upload dokumentasi publik" on storage.objects;
create policy "admin bendahara upload dokumentasi publik"
on storage.objects for insert
with check (
  bucket_id = 'koin-nu-public-documentation'
  and current_app_role() in ('admin', 'bendahara')
);

drop policy if exists "role terkait baca bukti privat" on storage.objects;
create policy "role terkait baca bukti privat"
on storage.objects for select
using (
  bucket_id = 'koin-nu-private-evidence'
  and (current_app_role() in ('admin', 'bendahara') or owner_id = auth.uid()::text)
);

drop policy if exists "role terkait upload bukti privat" on storage.objects;
create policy "role terkait upload bukti privat"
on storage.objects for insert
with check (
  bucket_id = 'koin-nu-private-evidence'
  and current_app_role() in ('admin', 'bendahara', 'petugas')
);

drop policy if exists "admin bendahara update bukti privat" on storage.objects;
create policy "admin bendahara update bukti privat"
on storage.objects for update
using (
  bucket_id = 'koin-nu-private-evidence'
  and current_app_role() in ('admin', 'bendahara')
);
