-- Migrasi modul Setoran Petugas dan Setor ke LAZISNU untuk SIKOINNU.
-- Jalankan pada Supabase SQL Editor setelah schema awal.

create table if not exists setoran_petugas (
  id bigint generated by default as identity primary key,
  nomor_setoran text not null unique,
  petugas_id bigint references petugas(id) on delete set null,
  tanggal_setor date not null,
  periode_mulai date not null,
  periode_selesai date not null,
  nominal numeric(14,2) not null default 0,
  jumlah_transaksi integer not null default 0,
  metode_setor text not null check (metode_setor in ('Tunai', 'Transfer', 'QRIS')),
  catatan_petugas text,
  bukti_setor_path text,
  bukti_setor_url text,
  bukti_setor_nama text,
  status text not null default 'Menunggu Verifikasi' check (status in ('Menunggu Verifikasi', 'Diterima Bendahara', 'Dikembalikan Revisi', 'Ditolak')),
  created_at timestamptz not null default now()
);

create table if not exists setoran_lazisnu (
  id bigint generated by default as identity primary key,
  nomor_setoran text not null unique,
  tanggal_setor date not null,
  tujuan_setoran text not null check (tujuan_setoran in ('LAZISNU Ranting', 'MWC LAZISNU', 'PC LAZISNU')),
  nama_penerima text not null,
  nominal numeric(14,2) not null default 0,
  metode_setor text not null check (metode_setor in ('Tunai', 'Transfer', 'QRIS')),
  nomor_bukti text,
  bukti_setor_path text,
  bukti_setor_url text,
  bukti_setor_nama text,
  catatan text,
  status text not null default 'Draft' check (status in ('Draft', 'Sudah Disetor', 'Batal')),
  created_at timestamptz not null default now()
);

alter table setoran_petugas enable row level security;
alter table setoran_lazisnu enable row level security;

drop policy if exists "admin bendahara baca setoran petugas" on setoran_petugas;
create policy "admin bendahara baca setoran petugas" on setoran_petugas for select using (current_app_role() in ('admin', 'bendahara'));
drop policy if exists "petugas baca setoran sendiri" on setoran_petugas;
create policy "petugas baca setoran sendiri" on setoran_petugas for select using (
  current_app_role() = 'petugas'
  and exists (select 1 from petugas p join profiles pr on pr.phone = p.phone where pr.id = auth.uid() and p.id = setoran_petugas.petugas_id)
);
drop policy if exists "petugas input setoran sendiri" on setoran_petugas;
create policy "petugas input setoran sendiri" on setoran_petugas for insert with check (current_app_role() in ('admin', 'petugas'));
drop policy if exists "admin bendahara petugas update setoran" on setoran_petugas;
drop policy if exists "admin bendahara update setoran petugas" on setoran_petugas;
create policy "admin bendahara update setoran petugas" on setoran_petugas for update using (current_app_role() in ('admin', 'bendahara')) with check (current_app_role() in ('admin', 'bendahara'));
drop policy if exists "petugas update setoran sendiri" on setoran_petugas;
create policy "petugas update setoran sendiri" on setoran_petugas for update using (
  current_app_role() = 'petugas'
  and exists (select 1 from petugas p join profiles pr on pr.phone = p.phone where pr.id = auth.uid() and p.id = setoran_petugas.petugas_id)
) with check (
  current_app_role() = 'petugas'
  and exists (select 1 from petugas p join profiles pr on pr.phone = p.phone where pr.id = auth.uid() and p.id = setoran_petugas.petugas_id)
);
drop policy if exists "admin hapus setoran petugas" on setoran_petugas;
create policy "admin hapus setoran petugas" on setoran_petugas for delete using (current_app_role() = 'admin');

drop policy if exists "role terkait baca setoran lazisnu" on setoran_lazisnu;
create policy "role terkait baca setoran lazisnu" on setoran_lazisnu for select using (current_app_role() in ('admin', 'bendahara', 'pengurus', 'petugas'));
drop policy if exists "admin bendahara kelola setoran lazisnu" on setoran_lazisnu;
create policy "admin bendahara kelola setoran lazisnu" on setoran_lazisnu for all using (current_app_role() in ('admin', 'bendahara')) with check (current_app_role() in ('admin', 'bendahara'));
