-- Koin NU Ranting Supabase schema
-- Jalankan file ini di Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  full_name text not null,
  role text not null default 'petugas' check (role in ('admin', 'bendahara', 'petugas', 'pengurus')),
  phone text,
  status text not null default 'aktif' check (status in ('aktif', 'tidak_aktif')),
  created_at timestamptz not null default now()
);

create table if not exists ranting_profile (
  id bigint generated by default as identity primary key,
  nama_ranting text not null,
  desa text not null,
  kecamatan text not null,
  kabupaten text not null,
  provinsi text not null,
  alamat_sekretariat text not null,
  email text,
  phone text,
  masa_khidmah text,
  logo_url text,
  created_at timestamptz not null default now()
);

create table if not exists pengurus (
  id bigint generated by default as identity primary key,
  nama text not null,
  jabatan text not null,
  phone text,
  alamat text,
  foto_url text,
  status text not null default 'aktif' check (status in ('aktif', 'tidak_aktif')),
  created_at timestamptz not null default now()
);

create table if not exists petugas (
  id bigint generated by default as identity primary key,
  nama text not null,
  phone text,
  alamat text,
  rt text,
  rw text,
  username text unique,
  wilayah_tugas text,
  status text not null default 'aktif' check (status in ('aktif', 'tidak_aktif')),
  created_at timestamptz not null default now()
);

create table if not exists donatur (
  id bigint generated by default as identity primary key,
  nama_kk text not null,
  alamat text,
  rt text,
  rw text,
  phone text,
  petugas_id bigint references petugas(id) on delete set null,
  kode_donatur text,
  qr_code_value text,
  qr_code_image text,
  status text not null default 'aktif' check (status in ('aktif', 'tidak_aktif')),
  catatan text,
  created_at timestamptz not null default now()
);

create table if not exists pengambilan_koin (
  id bigint generated by default as identity primary key,
  nomor_transaksi text not null unique,
  tanggal date not null,
  donatur_id bigint references donatur(id) on delete set null,
  petugas_id bigint references petugas(id) on delete set null,
  nominal numeric(14,2) not null default 0,
  metode_pembayaran text not null check (metode_pembayaran in ('Tunai', 'Transfer', 'QRIS')),
  catatan_petugas text,
  bukti_foto_path text,
  bukti_foto_url text,
  bukti_foto_nama text,
  status_verifikasi text not null default 'Menunggu Verifikasi' check (status_verifikasi in ('Menunggu Verifikasi', 'Disetujui Bendahara', 'Ditolak', 'Perlu Revisi')),
  status_notifikasi text not null default 'belum_dikirim' check (status_notifikasi in ('belum_dikirim', 'terkirim_wa', 'nomor_kosong', 'cetak_bukti', 'konfirmasi_manual')),
  waktu_notifikasi timestamptz,
  catatan_notifikasi text,
  riwayat_notifikasi jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists verifikasi_setoran (
  id bigint generated by default as identity primary key,
  pengambilan_id bigint not null references pengambilan_koin(id) on delete cascade,
  bendahara_id uuid references profiles(id) on delete set null,
  status text not null check (status in ('Disetujui Bendahara', 'Ditolak', 'Perlu Revisi')),
  catatan_bendahara text,
  bukti_setoran_path text,
  bukti_setoran_url text,
  bukti_setoran_nama text,
  tanggal_verifikasi date not null default current_date,
  created_at timestamptz not null default now()
);

create table if not exists setoran_petugas (
  id bigint generated by default as identity primary key,
  nomor_setoran text not null unique,
  petugas_id bigint references petugas(id) on delete set null,
  tanggal_setor date not null,
  periode_mulai date not null,
  periode_selesai date not null,
  nominal numeric(14,2) not null default 0,
  jumlah_transaksi integer not null default 0,
  metode_setor text not null check (metode_setor in ('Tunai', 'Transfer', 'QRIS')),
  catatan_petugas text,
  bukti_setor_path text,
  bukti_setor_url text,
  bukti_setor_nama text,
  status text not null default 'Menunggu Verifikasi' check (status in ('Menunggu Verifikasi', 'Diterima Bendahara', 'Dikembalikan Revisi', 'Ditolak')),
  created_at timestamptz not null default now()
);

create table if not exists setoran_lazisnu (
  id bigint generated by default as identity primary key,
  nomor_setoran text not null unique,
  tanggal_setor date not null,
  tujuan_setoran text not null check (tujuan_setoran in ('LAZISNU Ranting', 'MWC LAZISNU', 'PC LAZISNU')),
  nama_penerima text not null,
  nominal numeric(14,2) not null default 0,
  metode_setor text not null check (metode_setor in ('Tunai', 'Transfer', 'QRIS')),
  nomor_bukti text,
  bukti_setor_path text,
  bukti_setor_url text,
  bukti_setor_nama text,
  catatan text,
  status text not null default 'Draft' check (status in ('Draft', 'Sudah Disetor', 'Batal')),
  created_at timestamptz not null default now()
);

create table if not exists penyaluran_dana (
  id bigint generated by default as identity primary key,
  nomor_penyaluran text not null unique,
  tanggal date not null,
  nama_penerima text not null,
  alamat text,
  rt text,
  rw text,
  phone text,
  kategori_bantuan text not null,
  nominal numeric(14,2) not null default 0,
  sumber_dana text,
  status text not null default 'Draft' check (status in ('Draft', 'Disalurkan', 'Dibatalkan')),
  keterangan text,
  dokumentasi_path text,
  dokumentasi_url text,
  dokumentasi_nama text,
  created_at timestamptz not null default now()
);

create table if not exists dokumentasi_kegiatan (
  id bigint generated by default as identity primary key,
  judul text not null,
  kategori text not null,
  tanggal date not null,
  foto_path text,
  foto_url text not null,
  foto_nama text,
  created_at timestamptz not null default now()
);

create table if not exists settings (
  id text primary key,
  key text not null unique,
  value jsonb not null default 'null'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table pengambilan_koin add column if not exists bukti_foto_url text;
alter table pengambilan_koin add column if not exists bukti_foto_nama text;
alter table pengambilan_koin add column if not exists bukti_foto_path text;
alter table pengambilan_koin add column if not exists status_notifikasi text not null default 'belum_dikirim';
alter table pengambilan_koin add column if not exists waktu_notifikasi timestamptz;
alter table pengambilan_koin add column if not exists catatan_notifikasi text;
alter table pengambilan_koin add column if not exists riwayat_notifikasi jsonb not null default '[]'::jsonb;
alter table verifikasi_setoran add column if not exists bukti_setoran_url text;
alter table verifikasi_setoran add column if not exists bukti_setoran_nama text;
alter table verifikasi_setoran add column if not exists bukti_setoran_path text;
alter table penyaluran_dana add column if not exists dokumentasi_url text;
alter table penyaluran_dana add column if not exists dokumentasi_nama text;
alter table penyaluran_dana add column if not exists dokumentasi_path text;
alter table dokumentasi_kegiatan add column if not exists foto_path text;
alter table donatur add column if not exists kode_donatur text;
alter table donatur add column if not exists qr_code_value text;
alter table donatur add column if not exists qr_code_image text;

update donatur
set kode_donatur = 'DON-' || lpad(coalesce(rt, '0'), 3, '0') || '-' || lpad(coalesce(rw, '0'), 3, '0') || '-' || lpad(id::text, 4, '0')
where kode_donatur is null or kode_donatur = '';

update donatur
set qr_code_value = kode_donatur
where qr_code_value is null or qr_code_value = '';

create unique index if not exists donatur_kode_donatur_unique on donatur (kode_donatur);

create or replace function current_app_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((select role from profiles where id = auth.uid()), 'publik');
$$;

alter table profiles enable row level security;
alter table ranting_profile enable row level security;
alter table pengurus enable row level security;
alter table petugas enable row level security;
alter table donatur enable row level security;
alter table pengambilan_koin enable row level security;
alter table verifikasi_setoran enable row level security;
alter table setoran_petugas enable row level security;
alter table setoran_lazisnu enable row level security;
alter table penyaluran_dana enable row level security;
alter table dokumentasi_kegiatan enable row level security;
alter table settings enable row level security;

create policy "admin semua profiles" on profiles for all using (current_app_role() = 'admin') with check (current_app_role() = 'admin');
create policy "user baca profil sendiri" on profiles for select using (id = auth.uid());

create policy "ranting publik baca" on ranting_profile for select using (true);
create policy "admin kelola ranting" on ranting_profile for all using (current_app_role() = 'admin') with check (current_app_role() = 'admin');

create policy "pengurus publik baca aktif" on pengurus for select using (status = 'aktif');
create policy "admin kelola pengurus" on pengurus for all using (current_app_role() = 'admin') with check (current_app_role() = 'admin');

create policy "admin bendahara baca petugas" on petugas for select using (current_app_role() in ('admin', 'bendahara'));
create policy "admin kelola petugas" on petugas for all using (current_app_role() = 'admin') with check (current_app_role() = 'admin');

create policy "admin bendahara semua donatur" on donatur for select using (current_app_role() in ('admin', 'bendahara'));
create policy "petugas baca donatur wilayah" on donatur for select using (
  current_app_role() = 'petugas'
  and exists (
    select 1 from petugas p
    join profiles pr on pr.phone = p.phone
    where pr.id = auth.uid()
      and (p.id = donatur.petugas_id or (p.rt = donatur.rt and p.rw = donatur.rw))
  )
);
create policy "admin bendahara kelola donatur" on donatur for all using (current_app_role() in ('admin', 'bendahara')) with check (current_app_role() in ('admin', 'bendahara'));

create policy "admin bendahara baca pengambilan" on pengambilan_koin for select using (current_app_role() in ('admin', 'bendahara'));
create policy "petugas baca transaksi milik" on pengambilan_koin for select using (
  current_app_role() = 'petugas'
  and exists (
    select 1 from petugas p
    join profiles pr on pr.phone = p.phone
    where pr.id = auth.uid() and p.id = pengambilan_koin.petugas_id
  )
);
create policy "petugas input transaksi" on pengambilan_koin for insert with check (current_app_role() in ('admin', 'petugas'));
create policy "admin petugas update transaksi" on pengambilan_koin for update using (current_app_role() in ('admin', 'petugas', 'bendahara')) with check (current_app_role() in ('admin', 'petugas', 'bendahara'));

create policy "admin bendahara baca verifikasi" on verifikasi_setoran for select using (current_app_role() in ('admin', 'bendahara'));
create policy "bendahara verifikasi" on verifikasi_setoran for insert with check (current_app_role() in ('admin', 'bendahara'));

create policy "admin bendahara baca setoran petugas" on setoran_petugas for select using (current_app_role() in ('admin', 'bendahara'));
create policy "petugas baca setoran sendiri" on setoran_petugas for select using (
  current_app_role() = 'petugas'
  and exists (
    select 1 from petugas p
    join profiles pr on pr.phone = p.phone
    where pr.id = auth.uid() and p.id = setoran_petugas.petugas_id
  )
);
create policy "petugas input setoran sendiri" on setoran_petugas for insert with check (current_app_role() in ('admin', 'petugas'));
create policy "admin bendahara update setoran petugas" on setoran_petugas for update using (current_app_role() in ('admin', 'bendahara')) with check (current_app_role() in ('admin', 'bendahara'));
create policy "petugas update setoran sendiri" on setoran_petugas for update using (
  current_app_role() = 'petugas'
  and exists (
    select 1 from petugas p
    join profiles pr on pr.phone = p.phone
    where pr.id = auth.uid() and p.id = setoran_petugas.petugas_id
  )
) with check (
  current_app_role() = 'petugas'
  and exists (
    select 1 from petugas p
    join profiles pr on pr.phone = p.phone
    where pr.id = auth.uid() and p.id = setoran_petugas.petugas_id
  )
);
create policy "admin hapus setoran petugas" on setoran_petugas for delete using (current_app_role() = 'admin');

create policy "role terkait baca setoran lazisnu" on setoran_lazisnu for select using (current_app_role() in ('admin', 'bendahara', 'pengurus', 'petugas'));
create policy "admin bendahara kelola setoran lazisnu" on setoran_lazisnu for all using (current_app_role() in ('admin', 'bendahara')) with check (current_app_role() in ('admin', 'bendahara'));

create policy "publik baca penyaluran aman" on penyaluran_dana for select using (status = 'Disalurkan');
create policy "admin bendahara kelola penyaluran" on penyaluran_dana for all using (current_app_role() in ('admin', 'bendahara')) with check (current_app_role() in ('admin', 'bendahara'));

create policy "publik baca dokumentasi kegiatan" on dokumentasi_kegiatan for select using (true);
create policy "admin bendahara kelola dokumentasi kegiatan" on dokumentasi_kegiatan for all using (current_app_role() in ('admin', 'bendahara')) with check (current_app_role() in ('admin', 'bendahara'));

create policy "admin bendahara baca settings" on settings for select using (current_app_role() in ('admin', 'bendahara', 'pengurus'));
create policy "admin kelola settings" on settings for all using (current_app_role() = 'admin') with check (current_app_role() = 'admin');

create or replace view public_transparansi_pengambilan as
select tanggal, nominal, metode_pembayaran, status_verifikasi
from pengambilan_koin
where status_verifikasi = 'Disetujui Bendahara';

create or replace view public_transparansi_penyaluran as
select tanggal, kategori_bantuan, nominal, status
from penyaluran_dana
where status = 'Disalurkan';

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'koin-nu-public-documentation',
  'koin-nu-public-documentation',
  true,
  2097152,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "publik baca dokumentasi storage"
on storage.objects for select
using (bucket_id = 'koin-nu-public-documentation');

create policy "admin bendahara upload dokumentasi publik"
on storage.objects for insert
with check (
  bucket_id = 'koin-nu-public-documentation'
  and current_app_role() in ('admin', 'bendahara')
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'koin-nu-private-evidence',
  'koin-nu-private-evidence',
  false,
  2097152,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "role terkait baca bukti privat"
on storage.objects for select
using (
  bucket_id = 'koin-nu-private-evidence'
  and (current_app_role() in ('admin', 'bendahara') or owner_id = auth.uid()::text)
);

create policy "role terkait upload bukti privat"
on storage.objects for insert
with check (
  bucket_id = 'koin-nu-private-evidence'
  and current_app_role() in ('admin', 'bendahara', 'petugas')
);

create policy "admin bendahara update bukti privat"
on storage.objects for update
using (
  bucket_id = 'koin-nu-private-evidence'
  and current_app_role() in ('admin', 'bendahara')
);
